apiVersion: v1
kind: Service
metadata:
  name: devops-demo-svc

spec:
  type: NodePort    # Expose on a port of the node (good for local testing)

  selector:
    app: devops-demo

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # Access the app at http://<NodeIP>:30080