# Number of pod replicas
replicaCount: 5

image:
  repository: YOUR_DOCKERHUB_USERNAME/devops-demo
  tag: v1.1.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "64Mi"
    cpu: "100m"

# Service Account
serviceAccount:
  create: false
  annotations: {}
  name: ""

# Ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: devops-demo.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# HTTPRoute (Gateway API)
httpRoute:
  enabled: false

# Horizontal Pod Autoscaler (HPA)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80